config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return full title
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
    <h1>Sample App</h1>
    <p>
      This is the home page for the <a href="http://www.railstutorial.org">Ruby on Rails Tutorial</a> sample application.
    </p>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Static Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>